package:
  format-version: "1.0.0"
  name: "touch_host_driver_apps"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"

  dependencies:
    - name: "touch_host_driver"
      type: "package"
      version: "v1.1.0"
